'use client';

/**
 * The queue of shops saying "I have paid you".
 *
 * THIS SCREEN IS THE ANSWER TO "HOW DO I KNOW WHICH PLAN THEY BOUGHT".
 *
 * Without it the operator's only record of a shop's intention is a WhatsApp
 * conversation and a UPI credit for ₹149 — and ₹149 is a Starter month for
 * every one of a hundred shops, so matching money to a shop means scrolling
 * back through chats. Here the shop declared the plan and the months when it
 * submitted, the server priced them, and the row shows all of it beside the
 * screenshot and the UPI id the money left. The operator compares one figure
 * against their bank feed and presses a button.
 *
 * The code is generated by the server and shown ONCE. It cannot be read back —
 * the row keeps only a bcrypt hash — so the dialog holding it also holds the
 * WhatsApp link that sends it, with the message already written.
 */

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { useToast } from '@/components/ui/Toast';
import { EmptyState } from '@/components/ui/EmptyState';
import { WhatsAppIcon } from '@/components/ui/Icon';
import { formatPaise } from '@/lib/money';
import { PLAN_SPECS, type Plan } from '@/lib/plans';
import { LOCALES, LOCALE_LABELS, type Locale } from '@/lib/i18n';

export type AdminPaymentRequest = {
  id: string;
  shopName: string;
  shopSlug: string;
  shopPhone: string;
  plan: Plan;
  months: number;
  amountPaise: number;
  payerUpiId: string;
  payerPhone: string;
  screenshotData: string;
  status: 'SUBMITTED' | 'CODE_ISSUED' | 'ACTIVATED' | 'REJECTED';
  attempts: number;
  reviewNote: string;
  /** ISO, for sorting only — never formatted during render. */
  createdAt: string;
  /**
   * The date already written out, on the server.
   *
   * `toLocaleString` during render is a hydration mismatch waiting to happen:
   * Node formats in the server's timezone and the browser in the operator's, so
   * the two produce different text for the same instant and React throws the
   * whole tree away and re-renders it. Formatting once, server-side, is both
   * correct and cheaper.
   */
  createdLabel: string;
};

type IssuedCode = {
  code: string;
  shopName: string;
  shopPhone: string;
  ownerName: string;
  planName: string;
  months: number;
  renewsOn: string;
  defaultLocale: Locale;
  /** The whole message, ready to send, in each language. */
  messages: Record<Locale, string>;
};

export function PaymentRequestsPanel({ requests }: { requests: AdminPaymentRequest[] }) {
  const router = useRouter();
  const { push } = useToast();
  const [busyId, setBusyId] = useState<string | null>(null);
  const [issued, setIssued] = useState<IssuedCode | null>(null);
  // Which language the operator will send in. Seeded from the shop's own.
  const [lang, setLang] = useState<Locale>('en');
  const [copied, setCopied] = useState(false);
  const [zoom, setZoom] = useState<AdminPaymentRequest | null>(null);
  const [rejecting, setRejecting] = useState<AdminPaymentRequest | null>(null);
  const [rejectNote, setRejectNote] = useState('');

  async function act(row: AdminPaymentRequest, body: Record<string, unknown>) {
    setBusyId(row.id);
    try {
      const response = await fetch(`/api/admin/payments/${row.id}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const result = await response.json();
      if (!response.ok) {
        push(result.error ?? 'Could not do that', 'error');
        return;
      }
      if (result.code) {
        setIssued({
          code: result.code,
          shopName: result.shopName ?? row.shopName,
          shopPhone: result.shopPhone ?? row.shopPhone,
          ownerName: result.ownerName ?? '',
          planName: result.planName ?? '',
          months: result.months ?? row.months,
          renewsOn: result.renewsOn ?? '',
          defaultLocale: result.defaultLocale ?? 'en',
          messages: result.messages ?? {},
        });
        setLang(result.defaultLocale ?? 'en');
      } else {
        push('Request refused', 'success');
      }
      router.refresh();
    } catch {
      push('Network problem — please try again', 'error');
    } finally {
      setBusyId(null);
      setRejecting(null);
      setRejectNote('');
    }
  }

  if (requests.length === 0) {
    return (
      <EmptyState
        title="No payment requests"
        hint="When a shop pays and sends its screenshot, it appears here for you to check."
      />
    );
  }

  return (
    <>
      <ul className="space-y-3">
        {requests.map((row) => (
          <li
            key={row.id}
            className="rounded-2xl border border-slate-200 bg-white p-4 shadow-card"
          >
            <div className="flex flex-wrap items-start gap-4">
              {/* The screenshot first and small. It is evidence, not content —
                  the operator glances at it and goes to the numbers. */}
              {row.screenshotData ? (
                <button
                  type="button"
                  onClick={() => setZoom(row)}
                  className="h-20 w-20 shrink-0 overflow-hidden rounded-xl border border-slate-200"
                  aria-label={`See ${row.shopName}'s payment screenshot`}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={row.screenshotData} alt="" className="h-full w-full object-cover" />
                </button>
              ) : (
                <span className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl border border-dashed border-slate-300 text-center text-xs text-slate-400">
                  No proof
                </span>
              )}

              <div className="min-w-0 flex-1">
                <p className="flex flex-wrap items-baseline gap-x-2">
                  <a
                    href={`/admin/shop/${row.shopSlug}`}
                    className="font-bold text-slate-900 underline decoration-slate-300"
                  >
                    {row.shopName}
                  </a>
                  <StatusPill status={row.status} />
                </p>

                {/* THE LINE THAT MATTERS: what they say they bought, and what
                    that costs. One glance against a bank feed. */}
                <p className="mt-1 text-sm text-slate-700">
                  <strong>{PLAN_SPECS[row.plan]?.name ?? row.plan}</strong> ·{' '}
                  {row.months === 12 ? '1 year' : `${row.months} month${row.months === 1 ? '' : 's'}`}{' '}
                  · <strong className="tabular-nums text-brand-700">{formatPaise(row.amountPaise)}</strong>
                </p>

                {/* The shop's own number leads, because it is the one that is
                    always there and the one you will WhatsApp the code to. The
                    payer fields are only shown when something filled them —
                    the owner's form stopped asking, since it was making a
                    shopkeeper retype an identifier the screenshot already
                    shows, but a gateway could still write them later. */}
                <p className="mt-1 break-all text-xs text-slate-500">
                  {row.shopPhone}
                  {row.payerUpiId && ` · ${row.payerUpiId}`}
                  {row.payerPhone && ` · ${row.payerPhone}`} · {row.createdLabel}
                </p>

                {row.status === 'CODE_ISSUED' && (
                  <p className="mt-1 text-xs font-medium text-amber-700">
                    Code sent, not used yet
                    {row.attempts > 0 && ` · ${row.attempts} wrong ${row.attempts === 1 ? 'try' : 'tries'}`}
                  </p>
                )}
                {row.status === 'REJECTED' && row.reviewNote && (
                  <p className="mt-1 text-xs text-red-700">Refused: {row.reviewNote}</p>
                )}
              </div>

              {row.status !== 'ACTIVATED' && (
                <div className="flex shrink-0 flex-wrap gap-2">
                  <Button
                    onClick={() => void act(row, { action: 'issue' })}
                    loading={busyId === row.id}
                    disabled={busyId !== null}
                  >
                    {row.status === 'CODE_ISSUED' ? 'New code' : 'Issue code'}
                  </Button>
                  {row.status !== 'REJECTED' && (
                    <Button
                      variant="secondary"
                      onClick={() => setRejecting(row)}
                      disabled={busyId !== null}
                    >
                      Refuse
                    </Button>
                  )}
                </div>
              )}
            </div>
          </li>
        ))}
      </ul>

      {/* The code, once. There is no way back to this string. */}
      <Modal
        open={issued !== null}
        title="Send this code to the shop"
        tone="success"
        size="md"
        onClose={() => setIssued(null)}
        footer={
          <>
            <Button variant="secondary" onClick={() => setIssued(null)}>
              Done
            </Button>
            {issued && (
              <a
                href={`https://wa.me/91${issued.shopPhone}?text=${encodeURIComponent(
                  issued.messages[lang] ?? '',
                )}`}
                target="_blank"
                rel="noreferrer"
                className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#25D366] px-5 text-sm font-semibold text-white"
              >
                <WhatsAppIcon className="h-5 w-5" />
                Send on WhatsApp
              </a>
            )}
          </>
        }
      >
        {issued && (
          <>
            <p className="text-center text-5xl font-bold tracking-[0.3em] tabular-nums text-slate-900">
              {issued.code}
            </p>
            <p className="mt-2 text-center text-sm">
              <strong>{issued.shopName}</strong>
              {issued.ownerName && <> · {issued.ownerName}</>}
              <br />
              {issued.planName} · {issued.months === 12 ? '1 year' : `${issued.months} month(s)`}
              {issued.renewsOn && <> · until {issued.renewsOn}</>}
            </p>

            {/* WHICH LANGUAGE TO SEND IN. The shop's own is preselected, but the
                operator knows things the locale column does not — that this
                shopkeeper reads Hindi, or that the number belongs to a son who
                reads English. */}
            <div
              role="group"
              aria-label="Message language"
              className="mt-4 inline-flex rounded-xl bg-slate-100 p-1"
            >
              {LOCALES.map((option) => (
                <button
                  key={option}
                  type="button"
                  aria-pressed={lang === option}
                  onClick={() => {
                    setLang(option);
                    setCopied(false);
                  }}
                  className={
                    'rounded-lg px-3 py-1.5 text-sm font-semibold transition ' +
                    (lang === option
                      ? 'bg-white text-slate-900 shadow-sm'
                      : 'text-slate-600 hover:text-slate-900')
                  }
                >
                  {LOCALE_LABELS[option]}
                  {option === issued.defaultLocale && (
                    <span className="ml-1 text-xs font-normal text-slate-400">(shop)</span>
                  )}
                </button>
              ))}
            </div>

            {/* The exact text that will be sent, not a description of it. An
                operator about to message a customer should be able to read it
                first — and on a desktop where WhatsApp Web is not signed in,
                copying it is the only way to send it at all. */}
            <pre className="mt-2 max-h-56 overflow-y-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 font-sans text-sm text-slate-700">
              {issued.messages[lang]}
            </pre>

            <button
              type="button"
              onClick={async () => {
                try {
                  await navigator.clipboard.writeText(issued.messages[lang] ?? '');
                  setCopied(true);
                } catch {
                  push('Could not copy — select the text instead', 'error');
                }
              }}
              className="mt-2 text-sm font-semibold text-brand-700 underline"
            >
              {copied ? 'Copied' : 'Copy message'}
            </button>

            <p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-amber-900">
              This is the only time you will see the code. It is stored hashed, exactly like a
              password, so nothing can read it back — send it before you close this.
            </p>
          </>
        )}
      </Modal>

      <Modal
        open={zoom !== null}
        title={zoom ? `${zoom.shopName} — payment proof` : ''}
        size="md"
        onClose={() => setZoom(null)}
        footer={
          <Button variant="secondary" onClick={() => setZoom(null)}>
            Close
          </Button>
        }
      >
        {zoom?.screenshotData && (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={zoom.screenshotData} alt="" className="w-full rounded-xl" />
        )}
      </Modal>

      <Modal
        open={rejecting !== null}
        title="Refuse this request"
        tone="danger"
        onClose={() => setRejecting(null)}
        footer={
          <>
            <Button variant="secondary" onClick={() => setRejecting(null)}>
              Cancel
            </Button>
            <Button
              variant="danger"
              loading={busyId !== null}
              onClick={() =>
                rejecting && void act(rejecting, { action: 'reject', reviewNote: rejectNote })
              }
            >
              Refuse
            </Button>
          </>
        }
      >
        <p>The shop sees this reason in their app, so write it for them.</p>
        <input
          value={rejectNote}
          onChange={(event) => setRejectNote(event.target.value)}
          maxLength={200}
          placeholder="We could not find this payment"
          className="mt-3 w-full rounded-xl border border-slate-300 px-3 py-2.5"
        />
      </Modal>
    </>
  );
}

/*
 * The message used to be built here, in English, from four facts.
 *
 * It named a plan and a code and nothing else — not the shop, not the owner,
 * not the date the plan runs to. An operator working several shops from one
 * phone could send it to the wrong number with nothing in the text to give that
 * away, and the shopkeeper's only receipt for money they had just sent said
 * neither what they had bought nor until when.
 *
 * It is composed on the server now (lib/activation-message.ts), in all three
 * languages, from the same `periodFor` arithmetic that will grant the time — so
 * the renewal date quoted here is the one the shop actually gets.
 */

function StatusPill({ status }: { status: AdminPaymentRequest['status'] }) {
  const look: Record<AdminPaymentRequest['status'], [string, string]> = {
    SUBMITTED: ['Waiting for you', 'bg-amber-100 text-amber-900'],
    CODE_ISSUED: ['Code sent', 'bg-blue-100 text-blue-900'],
    ACTIVATED: ['Activated', 'bg-brand-100 text-brand-800'],
    REJECTED: ['Refused', 'bg-red-100 text-red-800'],
  };
  const [label, classes] = look[status];
  return (
    <span className={`rounded-full px-2 py-0.5 text-xs font-bold uppercase tracking-wide ${classes}`}>
      {label}
    </span>
  );
}
